### ISSUE TITLE
Error 400: The request cannot be fulfilled due to bad syntax

### ISSUE THREAD

**Issue by Loxej** [keotl/ohdieux#10]
Erreur lors de l'ajout du podcast#3858 (midi-info) sur l'appli Podcast Addict. Les épisodes n'apparaissent jamais. C'est le seul podcast qui me cause ce problème.

**Comment by keotl** [comment]
Il semble que Midi info comporte un épisode invalide qui faisait planter le parser, spécifiquement [celui-ci](https://ici.radio-canada.ca/ohdio/premiere/emissions/midi-info/episodes/367273/audio-fil-du-lundi-7-novembre-2016) ne comporte aucun flux audio. Je viens d'apporter un correctif pour ignorer ce genre d'objets invalides. 

Comme il s'agit d'un balado comportant un très grand nombre d'épisodes, il se pourrait que cela prenne plusieurs minutes avant que le fichier RSS ne soit généré et mis en cache. Il se pourrait que vous ayez à réessayer l'ajout plusieurs fois en attendant que le fichier soit prêt.
