### ISSUE TITLE
Ne fonctionne pas sur Google Podcast.

### ISSUE THREAD

**Issue by Sgtmoustache** [keotl/ohdieux#12]
Salut!

J'utilise l'application de Google Podcast et lorsque j'ajoute le feed RSS je vois bien les épisodes apparaitre mais j'ai un message d'erreur lorsque j'essai de lancer un des podcasts : 

![image](https://github.com/keotl/ohdieux/assets/16720916/ef4a456c-54e6-4df4-b22e-6b97e84beab9)

![image](https://github.com/keotl/ohdieux/assets/16720916/2f2e0357-c20a-4ec0-804a-f95ab640c360)

**Comment by keotl** [comment]
Salut, je crois qu'il s'agit là d'un problème de formats supportés. Ohdieux fonctionne en créant un feed RSS qui pointe directement sur les fichiers audio utilisés par Ohdio, soit des stream HLS (fichiers .m3u8) qui ne semblent pas supportés par Google Podcasts d'après [cette page](https://support.google.com/podcast-publishers/answer/9889544?hl=en).

D'autres gens ont réussi à faire ajouter le support pour les streams HLS dans d'autres lecteurs de podcasts open source comme Pocket Casts, donc cela pourrait être une alternative possible, voir #4 .

**Comment by arthurlutz** [comment]
Une alternative (pas très accessible pour les non geeks) est d'utiliser le flux rss fourni avec l'excellent yt-dlp https://github.com/yt-dlp/yt-dlp : 

```
yt-dlp --trim-filename 50 --downloader ffmpeg --hls-use-mpegts --extract-audio --audio-format mp3 "https://ohdieux.ligature.ca/rss?programme_id=7907"
```

Bon, après faut trouver un moyen de les lire dans un lecteur de podcast, mais au moins on a accès aux fichiers dans des formats plus accessibles.

**Comment by arthurlutz** [comment]
@keotl il me semeble que Pocket Casts n'est pas open source, est-ce que tu as d'autres lecteurs de podcasts auquel tu pensais ?

**Comment by keotl** [comment]
@arthurlutz Très intéressant le one-liner pour télécharger l'entièreté du podcast. Effectivement, la seule manière d'avoir une vraie compatibilité universelle serait de convertir les fichiers audio, ce qui est simplement trop coûteux pour le genre de traffic présentement géré par ohdieux.

J'ai personnellement essayé Apple Podcasts, et certains utilisateurs rapportent utiliser Pocket Casts et AntennaPod. (#10 #4 ) Je viens d'ouvrir #14 pour rassembler ce genre de discussions.

**Comment by gitphobic** [comment]
Ça ne fonctionne peut-être pas tout le temps, mais il semble que tu peux télécharger l'audio directement si tu remplaces la fin du lien `master.m3u8` par `128.aac`.

Par exemple, pour le flux https://ohdieux.ligature.ca/rss?programme_id=7907, le premier audio est https://rcavmedias.akamaized.net/5dff8afe-293a-4a93-81de-8a077ff4b33b/2020-12-04_17_14_00_villagedansloreilleweb_0000/master.m3u8 => https://rcavmedias.akamaized.net/5dff8afe-293a-4a93-81de-8a077ff4b33b/2020-12-04_17_14_00_villagedansloreilleweb_0000/128.aac

Pour un balado plus récent (10790):
https://rcavmedias-static.akamaized.net/hls/0d6337d2-8ff8-41ef-942d-dc0c2204837c/2023-05-17_05_01_00_bonvoyageohdio_0000_master.m3u8 => https://rcavmedias-static.akamaized.net/hls/0d6337d2-8ff8-41ef-942d-dc0c2204837c/2023-05-17_05_01_00_bonvoyageohdio_0000_128.aac

**Comment by gitphobic** [comment]
Ça ne fonctionne pas sur les vieux balados, mais il semble que pour les nouveaux tu peux télécharger l'audio directement si tu remplaces la fin du lien `master.m3u8` par `128.aac`.

Par exemple, le balado (10790):
https://rcavmedias-static.akamaized.net/hls/0d6337d2-8ff8-41ef-942d-dc0c2204837c/2023-05-17_05_01_00_bonvoyageohdio_0000_master.m3u8 => https://rcavmedias-static.akamaized.net/hls/0d6337d2-8ff8-41ef-942d-dc0c2204837c/2023-05-17_05_01_00_bonvoyageohdio_0000_128.aac

**Comment by gitphobic** [comment]
Un peu plus de recherche m'a parmis de découvrir que les appels de téléchargement de l'app appelaient un autre serveur: `https://rcavmedias-download.akamaized.net/mp4/{episode-uuid}/{episode-slug}_128.mp4`

J'ai testé avec un nouveau balado et un vieux :

https://rcavmedias-static.akamaized.net/hls/0d6337d2-8ff8-41ef-942d-dc0c2204837c/2023-05-17_05_01_00_bonvoyageohdio_0000_master.m3u8
=> https://rcavmedias-download.akamaized.net/mp4/0d6337d2-8ff8-41ef-942d-dc0c2204837c/2023-05-17_05_01_00_bonvoyageohdio_0000_128.mp4

https://rcavmedias.akamaized.net/5dff8afe-293a-4a93-81de-8a077ff4b33b/2020-12-04_17_14_00_villagedansloreilleweb_0000/master.m3u8
=> https://rcavmedias-download.akamaized.net/mp4/5dff8afe-293a-4a93-81de-8a077ff4b33b/2020-12-04_17_14_00_villagedansloreilleweb_0000_128.mp4

**Comment by keotl** [comment]
@gitphobic Très intéressant! Ça permettrait d'améliorer de beaucoup la compatibilité avec les autres players.

**Comment by keotl** [comment]
@gitphobic @Sgtmoustache Je viens d'effectuer le changement pour servir les fichiers audio sous format mp4 plutôt que HLS dans #15 . Cela devrait logiquement corriger tous les problèmes de compatibilité et de téléchargements d'un seul coup.
