### ISSUE TITLE
Problème de mise à jour ?

### ISSUE THREAD

**Issue by smsisko** [keotl/ohdieux#16]
Il semblerait que le site a arrêté de se mettre à jour le 28 juin.

J'ai essayé quelques balados journaliers, et tous semble avoir arrêté d'être mis à jour la même journée:

https://ohdieux.ligature.ca/rss?programme_id=302
https://ohdieux.ligature.ca/rss?programme_id=6896
https://ohdieux.ligature.ca/rss?programme_id=4586

**Comment by keotl** [comment]
De ce que j'ai pu voir dans les logs, le thread qui met à jour les programmes avait planté à cause d'une erreur transiente. #17 devrait faire en sorte que le thread redémarre correctement dans ces cas.
