### ISSUE TITLE
Les flux ne sont plus mis à jour.

### ISSUE THREAD

**Issue by rfjqc** [keotl/ohdieux#18]
Bonjour. Les flux ne sont plus mis à jour. Est-ce qu'il y a quelque chose à faire?

**Comment by keotl** [comment]
Bonjour, normalement tout devrait se mettre à jour automatiquement dans votre lecteur à mesure que de nouveaux épisodes sont disponibles. Si vous pouvez fournir le numéro de programme et/ou le lecteur de podcasts que vous utilisez, je pourrai jeter un œil et voir ce qui cloche.

**Comment by rfjqc** [comment]
Effectivement, ça vient de mon lecteur car celui de ma conjointe se met à jour. Pocket casts sur android dans les 2 cas. Version 7.48 pour moi. La seule chose que je vois, c'est que ça fait plus longtemps que j'utilise ton merveilleux système. Merci vraiment beaucoup! J'ai effacé et re-ajouté un flux et ça marche.

**Comment by keotl** [comment]
Pas de souci, n'hésite pas si ça bogue encore.
