### ISSUE TITLE
Midi info toggles between 30m and 1h

### ISSUE THREAD

**Issue by Sytten** [keotl/ohdieux#25]
**Description**
It looks like my podcast toggles between the half episode (30m) and the full episode (+1h). Unsure if its because the episode name is the same in the RSS feed, I will check.

**Pour reproduire / To Reproduce**
- Code d'émission / Programme ID : 3858
- Lecteur utilisé / Podcast player : Antenna Pod (Android)

**Comment by keotl** [comment]
You could try using the "Tag segment numbers" option on the website as a workaround. It will add (1), (2), ... to each episode title to differentiate them.
I ran into a very similar issue on earlier versions of Apple Podcasts and this was enough to fix it.

**Comment by Sytten** [comment]
That seems to work! The time for each segment is not correct but they ate there.
