### ISSUE TITLE
Limit number of episodes

### ISSUE THREAD

**Issue by Sytten** [keotl/ohdieux#26]
**Description**
Right now it fetches everything but for most shows you only care about the last X days. My player has trouble handling like a +1000 episodes.

Unsure how antenna pod processes the data but it took a solid 5 minutes to remove all the episodes when I switched the URL to use segments.

**Pour reproduire / To Reproduce**
- Code d'émission / Programme ID : 3858
- Lecteur utilisé / Podcast player : AntennaPod

**Comment by keotl** [comment]
I added a new toggle for limiting to the latest 50 episodes, which should be roughly 1 month for Midi-Info.

**Comment by Sytten** [comment]
Much faster to update thanks!
