### ISSUE TITLE
Beau Dommage: bande-annonce seulement 

### ISSUE THREAD

**Issue by philippec** [keotl/ohdieux#32]
**Description**

Le nouveau balado "Beau Dommage, la face cachée de l'album" ne présente que la bande-annonce sur Ohdieux alors que tous les épisodes sont disponibles:

https://ici.radio-canada.ca/ohdio/balados/11804/beau-dommage-la-face-cachee-de-album

**Pour reproduire / To Reproduce**

- Code d'émission / Programme ID : 11804
- Lecteur utilisé / Podcast player : Overcast

On peut bien voir le xml qui ne contient que la bande-annonce:

https://ohdieux.ligature.ca/rss?programme_id=11804

**Comment by keotl** [comment]
Je pense qu'il y a un bug avec le code de caching pour les programmes qui listent les épisodes en ordre chronologique. J'ai invalidé la cache manuellement pour 11804, mais je laisse ce issue ouvert en attendant de pouvoir ajouter un correctif plus permanent.

**Comment by philippec** [comment]
Je confirme que le téléchargement fonctionne maintenant. Merci!
