### ISSUE TITLE
Incorrectly parses date

### ISSUE THREAD

**Issue by lowesjam** [keotl/ohdieux#34]
**Description**
Trying to use ohdieux on the "Tellement Hockey" podcast: 
https://ici.radio-canada.ca/ohdio/balados/6104/tellement-hockey-martin-leclerc-alexandre-coupal-gascon
https://ohdieux.ligature.ca/rss?programme_id=6104
It appears to work correctly, but the first episode pubDate seems to be incorrectly parsed:

**Pour reproduire / To Reproduce**
- Code d'émission / Programme ID : 6104
- Lecteur utilisé / Podcast player : Overcast

Looking at https://ohdieux.ligature.ca/rss?programme_id=6104:

```
<item>
<enclosure url="https://rcavmedias-static.akamaized.net/mp4/e628ee1b-fbe3-4ec5-ba44-c8884c702e51/2024-07-02_15_25_54_tellementhockey_0000_128.mp4" length="3856" type="audio/mpeg"/>
<title> Juraj Slafkovsky... en solde! </title>
<description>
Kent Hughes offre un contrat à long terme à Juraj Slafkovsky. Est-ce que tout le monde y a trouvé son compte? Alexandre Burrows décide de prendre un pas de recul, après 23 ans sans interruption dans le hockey professionnel. Et collectivement, c'est plus de 1 milliard de dollars qui ont été dépensés sur le marché des joueurs autonomes dans la LNH, le 1er juillet.
</description>
<guid>929603_0</guid>
<itunes:author>Radio-Canada</itunes:author>
<itunes:duration>3856</itunes:duration>
<itunes:explicit>clean</itunes:explicit>
<pubDate>Tue, 28 May 2024 19:38:00 -0000</pubDate>               <-- should be 02 July not 28 May
</item>
```

Compare to : https://ici.radio-canada.ca/ohdio/balados/6104/tellement-hockey-martin-leclerc-alexandre-coupal-gascon/929603/burrows-recul-hockey-lnh-millions
which has: **"Épisode 336 - 2 juillet 2024"**

Thanks very much for your work in not only making the software freely available, but even providing a web service - so kind of you!

**Comment by keotl** [comment]
Hi there, thanks for the bug report. I think I've been able to find the root cause of this, so the date should now be accurate for 6104. I will be manually clearing the cache for other programmes over the next few days.

**Comment by lowesjam** [comment]
You are so kind for doing that- thank you very much!
