### ISSUE TITLE
Ne fonctionne pas pour les émissions qui ne sont pas des balados

### ISSUE THREAD

**Issue by Domingato** [keotl/ohdieux#36]
**Description**
Une émission qui n'est pas un balado donne un lien invalide avec erreur 500.

**Pour reproduire / To Reproduce**
- Code d'émission / Programme ID : 105966 
https://ici.radio-canada.ca/ohdio/livres-audio/105966/le-plongeur/a-propos
- Lecteur utilisé / Podcast player :  Antenna Pod

Ce serait vraiment bien de pouvoir accéder à l'ensemble du contenu d'Ohdio sur d'autres applications. Ohdio est pour moi une horreur.

**Comment by keotl** [comment]
Salut, je viens d'ajouter un support rudimentaire des livres audio. Comme leur format de données est un peu différent, quelques informations risquent d'être un peu aberrantes, comme la date de diffusion, mais autrement cela devrait fonctionner.
