### ISSUE TITLE
Doublons (4x) pour chaque épisode

### ISSUE THREAD

**Issue by sebthesun** [keotl/ohdieux#37]
**Description**
Chaque épisode se retrouve 4 fois dans la liste, toutefois, ce problème n'existe que pour l'émission 1124 -Tout un matin, les autres émissions auxquelles je suis abonnées n'ont pas ce problème (6104-Tellemen hockey, et  6056-Moteur de recherche)

**Pour reproduire / To Reproduce**
- 1124
- Lecteur utilisé / Podcast player : Android-PodcastAddict et Kubuntu24.04-Clementine

**Comment by keotl** [comment]
Salut, il s'agit d'une limitation de l'implémentation actuelle. Dans les faits, les émissions qui durent plus d'une heure sont généralement séparés en plusieurs fichiers audio sur les serveurs de RC, et donc ohdieux les affiche comme épisodes séparés pour éviter d'avoir à les re-transcoder.

L'option « Numéroter segments » ajoute (1), (2), etc. au titre de ces segments pour rendre cette distinction explicite, et « Inverser ordre segments » peut forcer un ordre inverse sur ces segments au cas où un lecteur se mettrait à les jouer en ordre inverse par défaut.
