### ISSUE TITLE
Lecture impossible sur Pocket Casts

### ISSUE THREAD

**Issue by philippemiron** [keotl/ohdieux#4]
Est-ce que vous avez une idée de ce que pourrait être le problème ? Le feed apparaît mais il y a un problème à la lecture ou au téléchargement d'épisodes.

Merci!

![Screenshot_20221119-122044.png](https://user-images.githubusercontent.com/387624/202863534-8c6254ee-af30-4ec4-83b3-d2bafd3f3155.png)

**Comment by keotl** [comment]
Salut, je viens d'essayer sur Pocket Casts sous iOS 16, et la lecture en ligne semble fonctionner, pourvu que je n'essaie pas de télécharger l'épisode du tout. Est-ce que vous parvenez à la faire fonctionner (partiellement) de cette manière?

**Comment by philippemiron** [comment]
Non ça ne foncitonne pas.. j'ai contacté l'équipe de Pocket Casts.

**Comment by keotl** [comment]
Je soupçonne que l'application ne supporte pas les streams HLS utilisés par Ohdio (fichiers .m3u8), du moins sur toute les plateformes. Il pourrait être pertinent de leur fournir cette information.

**Comment by smsisko** [comment]
J'ai soumis une feature request https://github.com/Automattic/pocket-casts-android/issues/670

**Comment by philippemiron** [comment]
J'ai discuté avec les devs sur leur Slack, en gros ils ont dit: certains médias (e.g. .m3u8) ne sont pas supporté sur toutes les plateformes. Ils ont une page avec les formats supporté, https://support.pocketcasts.com/article/supported-file-types-audio-video-web-player/.

**Comment by smsisko** [comment]
J'ai soumis un PR sur Pocket Casts et il a été accepté, la prochaine version sur Android devrait supporter HLS.

**Comment by philippemiron** [comment]
![Screenshot_20230126-213432.png](https://user-images.githubusercontent.com/387624/214998214-83383395-cfa4-4592-a884-71a557692d56.png)

👏👏
